Update to Electron v11
Breaking changes:

Since Electron v9, BrowserWindow.webPreferences.enableRemoteModule
is false in default.
https://www.electronjs.org/docs/breaking-changes#default-changed-enableremotemodule-defaults-to-false

Update to spectron to match Electron v11.
spectron depends on webdriverio v6, which api is different with v4.
(v4 => v5 has many command changes)
https://github.com/webdriverio/webdriverio/blob/v5/CHANGELOG.md#v500-2018-12-20

Add "buffer/" to whitelist of webpack-node-externals.
Thus avoids runtime error for integration test:
"Uncaught Error: Cannot find module 'buffer/'"
It might be resolved in latest webpack...? (I don't test yet)

Update electron-log to v4.
v3 causes UnhandledPromiseRejectionWarning.